# Generated by Django 6.0.5 on 2026-06-01 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25, verbose_name='نام')),
                ('lname', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('num', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='تلفن همراه را به درستی وارد کنید')], verbose_name='تلفن همراه')),
                ('user_name', models.CharField(max_length=23, verbose_name='نام کاربری')),
                ('password', models.CharField(validators=[django.core.validators.RegexValidator(message='رمز عبور باید حداقل 8 کاراکتر شامل حروف یا اعداد باشد', regex='^[a-zA-Z0-9]{8,}$')])),
                ('registerd_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
