# Generated by Django 4.2.16 on 2026-06-08 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25, verbose_name='نام')),
                ('lname', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('num', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='مثال: 09123456789')], verbose_name='تلفن همراه')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='نام پدر')),
                ('national_num', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید شامل 10 رقم باشد')], verbose_name='کد ملی')),
                ('degree', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=25, null=True, verbose_name='میزان تحصیلات')),
                ('national_card', models.FileField(blank=True, null=True, upload_to='cards/', verbose_name='تصویر کارت ملی')),
                ('sex', models.CharField(blank=True, choices=[('man', 'مرد'), ('woman', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('location', models.TextField(blank=True, null=True, verbose_name='محل سکونت')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس پرسنلی')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='تصویر مدرک تحصیلی')),
                ('birth_city', iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_info', to='iranian_cities.city', verbose_name='شهر محل تولد')),
                ('birth_province', iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_info', to='iranian_cities.province', verbose_name='استان محل تولد')),
                ('city', iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_info', to='iranian_cities.city', verbose_name='شهر محل سکونت')),
                ('province', iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_info', to='iranian_cities.province', verbose_name='استان محل سکونت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
