# Generated by Django 4.2.16 on 2026-06-13 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(error_messages={'max_length': 'نام نمی\u200cتواند بیشتر از ۲۵ کاراکتر باشد', 'required': 'لطفاً نام خود را وارد کنید'}, max_length=25, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(error_messages={'max_length': 'این فیلد نمی\u200cتواند بیشتر از ۲۵ کاراکتر باشد', 'required': 'لطفاً نام خانوادگی خود را وارد کنید'}, max_length=25, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num',
            field=models.CharField(error_messages={'required': 'لطفاً شماره تلفن همراه خود را وارد کنید'}, max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='مثال: 09123456789')], verbose_name='تلفن همراه'),
        ),
    ]
