# Generated by Django 6.0.5 on 2026-06-01 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='رمز عبور باید حداقل 8 کاراکتر شامل حروف یا اعداد باشد', regex='^[a-zA-Z0-9]{8,}$')]),
        ),
    ]
