# Generated by Django 6.0.5 on 2026-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='registerd_at',
            new_name='registered_at',
        ),
    ]
