# Generated by Django 6.0.5 on 2026-06-02 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_registerd_at_register_registered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25, verbose_name='نام')),
                ('lname', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('num', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='مثال: 09123456789')], verbose_name='تلفن همراه')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
