# Generated by Django 5.2.15 on 2026-06-05 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_delete_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='نام پدر')),
                ('national_num', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='کد ملی باید شامل 10 رقم باشد')], verbose_name='کد ملی')),
                ('degree', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], null=True, verbose_name='میزان تحصیلات')),
                ('national_card', models.FileField(blank=True, null=True, upload_to='cards/', verbose_name='تصویر کارت ملی')),
                ('sex', models.CharField(blank=True, choices=[('man', 'مرد'), ('woman', 'زن')], null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
