# Generated by Django 5.2.15 on 2026-06-06 09:00

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('registration', '0005_alter_profile_id_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='birth_city',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_info', to='iranian_cities.city', verbose_name='شهر محل تولد'),
        ),
        migrations.AddField(
            model_name='info',
            name='birth_province',
            field=iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_info', to='iranian_cities.province', verbose_name='استان محل تولد'),
        ),
        migrations.AddField(
            model_name='info',
            name='city',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_info', to='iranian_cities.city', verbose_name='شهر محل سکونت'),
        ),
        migrations.AddField(
            model_name='info',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='تصویر مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='info',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='محل سکونت'),
        ),
        migrations.AddField(
            model_name='info',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='عکس پرسنلی'),
        ),
        migrations.AddField(
            model_name='info',
            name='province',
            field=iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_info', to='iranian_cities.province', verbose_name='استان محل سکونت'),
        ),
        migrations.AlterField(
            model_name='info',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
